### ISSUE TITLE
Create proejct

### ISSUE THREAD

**Issue by abemscac** [abemscac/inet-PatrickKuei#1]
使用自己喜愛的工具建立前端專案 (`package.json` 已經建立好了，覆蓋的時候要小心，記得把`@commitlint`那些東西加回去)。
如果想試試看server-side rendering框架的話也可以趁現在，但是非必要。

**需求：**
- [ ] 建立專案(例如：使用某個cli建好專案，確定他可以跑就可以了，不必做任何改動)
- [ ] 確定`husky`的commitlint能正常運作 (在`npm install`之後，您還需要先執行一次`npm run prepare`)
- [ ] 加上`.prettier.json`，這樣所有開發者才會按照同樣的規則format code

**注意事項：**
- 我們有裝husky，規則是採用[conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)(例如：`feat: login page`)，所以commit的時候沒有照這個規則應該就會失敗，完整的commit規則請參考[這裡](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#rules)。
- `main`分支有加上push的保護機制，所以您沒有辦法直接把commit推到`main`上面。 所有的commits都必須經過以下流程，那些改動才會進到`main`：
  1.  先到Repository的[issues](https://github.com/abemscac/inet-PatrickKuei/issues)頁面看看自己想要做哪一個issue，並將issue的assignee設為自己。
  ![Screen Shot 2022-04-20 at 1 47 42 PM](https://user-images.githubusercontent.com/59676941/164160908-5014a2ad-b608-4442-8626-33a8b1f2d329.png)
  ![Screen Shot 2022-04-20 at 1 47 58 PM](https://user-images.githubusercontent.com/59676941/164160978-37b4f084-811f-4f4e-b41d-bb3f050d9fd9.png)
  2. 在本地切換到`main`，pull一次確定他是最新的。
  3. 從`main`建立一個本地分支，名稱為`{issue號碼}-簡單描述`。例如某個issue在Github上面的號碼是`9999`，title是`Hello World`，您的本地分支就可以取成`9999-hello-world`。後面的`hello-world`是可以自定的，好讀+好懂即可，但是前面的`9999-`請不要修改他。
  4. 開始在本地的`9999-hello-world`開發。
  5. 在開發期間`main`可能會有新的改動被merge回去，所以建議每天開始工作前先在本地pull最新的`main`，然後rebase您的本地開發分支onto `main`，確保您的本地開發分支不會太過老舊。如果`main`已經合併了一些commit，而您在本地也有其他commit，您的開發分支就會處於「既領先又落後」的狀態，像是`5↑6↓`。這時您只需要執行`git push --force-with-lease`讓git將本地rebase完的程式碼覆蓋掉remote的程式碼即可。您可以隨時將您的本地開發分支push到remote去，即使您還沒完成，或是裡面的程式碼一堆錯誤也完全沒問題，因為把開發分支推到remote的目的本來不是要他可以正常執行。這麼做的目的除了備份以外，也能讓其他開發者知道這個issue已經有人下手做了。
  6. 本地開發完成後再次重複第5步的rebase，並把最新的本地開發分支push到remote去。
  7. 建立pull request(PR)，有很多種方法，這裡只描述一種。到Github的[Pull requests](https://github.com/abemscac/inet-PatrickKuei/pulls)頁面，點選`New pull request`。
  ![Screen Shot 2022-04-20 at 1 40 11 PM](https://user-images.githubusercontent.com/59676941/164161055-d9d87f6b-dfec-46ca-8513-14af443cba04.png)
  然後在箭頭右方選擇您在remote上面的開發分支`9999-hello-world`。
  ![Screen Shot 2022-04-20 at 1 53 24 PM](https://user-images.githubusercontent.com/59676941/164161200-11a3ffed-4663-4d7d-8a22-6a1b7d396b31.png)
  點選Create pull request。
  ![Screen Shot 2022-04-20 at 1 55 01 PM](https://user-images.githubusercontent.com/59676941/164161217-2bb6f92e-8988-457f-94d6-78c4b9dc2ebf.png)
  之後請在PR description裡面輸入`Close #{issue編號}`，例如`Close #9999`。這樣當這個PR被merge回`main`的時候，被標記的issue也會一起被關閉。
  ![Screen Shot 2022-04-20 at 1 55 35 PM](https://user-images.githubusercontent.com/59676941/164161303-4ac305e4-9987-4d9d-b049-7637128c86d4.png)
  如果有任何問題/備註，也可以寫在PR description裡面。如果系統沒有幫您選擇reviewer，請在右方的reviewer列表中選擇一個合適的人選來檢視您的程式碼，完成之後點擊下方的Create pull request，PR就建立完成了。
  8. 之後reviewer就會開始檢視您的程式碼，中間也許會需要您對程式碼再進行一些改動，這時候請重複第6步，完成後不需要再建立新的PR，因為我們在第8步已經建立過了。
  9. Review完成之後管理者就會將您的PR rebase&merge回`main`，如此一來一個循環就完成了。Github流派的開發流程就是一直在做這個循環，直到專案完成。
- 等您將前端專案建好之後我們會加上Github actions，確保PR通過所有的測試，然後才由管理者rebase&merge回`main`。

**Comment by abemscac** [comment]
@PatrickKuei 報告patrick哥
這是您的第一個issue，對於需求有什麼問題的話都可以直接在issue底下留言
資訊/對話都留在Github上面，之後比較好找
另外他可以用@ tag人，對方會收到email，滿方便的
那些洋鬼子不管大小事也是整天@@@沒在客氣的，所以您可以放心的@下去
最近會慢慢把issue建起來，前面一些基礎建設的issue我會直接指派給您
差不多了之後您就可以自己決定要先從哪個issue開始做了

**Comment by PatrickKuei** [comment]
@abemscac 報告史蒂芬哥 原來如此
完全沒有使用過github這個功能 那究竟為什麼要使用jira那些東西呢 這看起來非常的簡單粗暴 難道是粗暴言論duck不必 政府主導 民眾自主應變 我負責 在那叫什麼.gif 嗎
沒問題史蒂芬哥 再麻煩您直接把怡秀指派給我了 我會好好省視這些怡秀來決定要先處理哪個怡秀

**Comment by abemscac** [comment]
報告是patrick哥
我記得如果曾經在issue裡面留言的話，只要底下有新留言，不管他有沒有@您，您都會收到email
這個Github issues比什麼拉機機拉好用多了，早說  怎麼不早說
太慢我們也不要了
等您把專案建立完成後我們就會開始指派一些年輕白大奶怡秀給您了

**Comment by PatrickKuei** [comment]
報告史蒂芬哥
我把專案clone下來之後 試著一整天手動設定webpack 各種config之類的
結果錯誤不斷 我的win7連node都放棄了也沒辦法跑
搞了一堆work around之後 一直跳typescript config啥files empty
網路上解法用了幾個之後還是放棄直接create-react-app了
我是先將您的base file備份 然後npx create-react-app之後 再把那些備份檔案抓回來 package.json之類的衝突調整一下
然後要commit的時候commitlint就爆了 
[Error: ENOENT: no such file or directory, open 'D:\kuei\前端\INET-PATRICKKUEI\.git\COMMIT_EDITMSG']

我決定用公司MAC再裝一次史蒂芬哥
可能win7真的太舊了

**Comment by abemscac** [comment]
抱歉patrick哥
專案裡面有個隱藏的`.git`資料夾，您可以試試在裡面建一個空的`COMMIT_EDITMSG`，這樣他可能就會動了
commitlint運作的原理是有個pre-commit的hook會在commit發生的時候把您的commit訊息複製到那個`./.git/COMMIT_EDITMSG`裡面，然後插件再去那個檔案抓內容，檢查看看有沒有符合我們設定的規範
node建議用16或以上，不過您的電腦可能已經有裝其他版本了
如果是這種情況的話nvm是個不錯的選擇，可以裝很多不一樣版本的node

**Comment by PatrickKuei** [comment]
原來如此史蒂芬哥
等等回去win7再試試 目前在mac上已經成功合併create-react-app和您的地基代碼 並且可以成功起動伺服器了
不過在push local上remote時 說要輸入帳號密碼
我輸入了自己的github帳密 不曉得有沒有打錯 不過目前是沒辦法push上來
想問一下史蒂芬哥您這組密碼是需要特殊暗號的嗎

**Comment by abemscac** [comment]
報告patrick哥
需要輸入身體密碼並附上新鮮截圖才能推送
這個repository是公開的，所以應該沒問題
Github後來都改成需要設定[personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)才可以push了，可能是這個問題嗎？
設定完成拿到token之後還需要修改您本地repository的origin url，原本是`https://github.com/abemscac/inet-PatrickKuei.git`，要改成`https://您的PAT@github.com/abemscac/inet-PatrickKuei.git`
例如說您的personal access token是`ilovebooby123`，repository的origin url就要改成`https://ilovebooby123@github.com/abemscac/inet-PatrickKuei.git`
這樣應該就可以push了

**Comment by abemscac** [comment]
報告patrick哥
以防萬一說一下，只要把issue裡面描述的東西做完就可以開PR了
例如說這個怡秀的目標是create project，所以只要建好專案確定他可以跑，PR列車就可以開起來了
一個PR通常都是對應一個改動，只有少部分情況才會偷渡 (例如很急著要，或是改動很細微不想再開issue)

**Comment by abemscac** [comment]
另外要選擇js或是ts都行
看您個人覺得哪個不做作有氣質
推薦是選ㄋㄟㄋㄟ大的  供您參考
