### ISSUE TITLE
As an user, I want to see navs

### ISSUE THREAD

**Issue by abemscac** [abemscac/inet-PatrickKuei#2]
身為一個使用者，我想要看到上方和左方的選單

![Screen Shot 2022-04-21 at 9 01 52 AM](https://user-images.githubusercontent.com/59676941/164350961-01476562-5c74-42ae-ad1c-328e2e4f8279.png)

**備註：**
這是一個feature，他底下會有多個implementation-story
真正可以被實踐的東西是implementation-story，feature是他們的parent，主要是用來描述這個大功能的全貌，然後追蹤底下的issue
例如說要造一輛車我們會需要方向盤、輪胎、引擎等等
「造車子」就會是一個feature，實作輪胎、實作方向盤、實作引擎就會是implementation-story
所以我們不會有`2-navs`這樣的branch，因為feature是抽象的，真正有實體的東西是他底下的那些implementation-story
正常的結構會是epic -> feature -> implementation-story
但是我們的功能小，epic對我們來說太大了，所以feature就夠了

- [x] #4
- [x] #5

**Comment by PatrickKuei** [comment]
報告史蒂芬哥
突然發現commitlint濕效了 隨便亂打都讓我commit
我切branch回還沒merge 的 main 或是checkout 之前的commit 都讓我過
是不是我改到啥git ignore的東西了 要來修一下了...

**Comment by PatrickKuei** [comment]
阿斯 原來如此 了解了史蒂芬哥
瘋狂做菜是feature  瞄準 插入 拔出 大爆身寸是implementation story

**Comment by PatrickKuei** [comment]
報告史蒂芬哥 這樣子的話我就直接將remote branch的 2-....... 刪掉就行了嗎
沒有刪過remote branch 只要按下ＯＫ就行了嗎
<img width="285" alt="image" src="https://user-images.githubusercontent.com/48916128/165071188-ee9126b2-ec2b-4374-9524-cc93181eb067.png">

**Comment by abemscac** [comment]
報告是patrick哥
您可以隨意刪除自己在remote建立的branch  沒有問題  記得勾下面那個Force Delete
只要確定其他人沒有在用那個branch就好
因為通常implementation story會拆成很小  一次由一個人負責
所以其他人不會碰到您的`2-navs-for-guest`才是  除非您把那個issue它交給其他人接手

這種情況您可以按照以下步驟來處理：

1. 直接rename local的branch (`git branch -M 4-navs-for-guest`)
2. Push`4-navs-for-guest`到remote，這樣remote就會同時有`2-navs-for-guest`和`4-navs-for-guest`；本地這裡就沒有`2-navs-for-guest`了
3. 刪除remote的`2-navs-for-guest`

或是您也可以：

1. 先切回local main，pull一次確定他是最新的
2. 從最新的local main建立新分支`4-navs-for-guest`
3. 從本地的`2-navs-for-guest` cherry-pick 您想要的改動到`4-navs-for-guest`
4. Push`4-navs-for-guest`到remote，這樣remote就會同時有`2-navs-for-guest`和`4-navs-for-guest`
5. 刪除本地和remote的`2-navs-for-guest`

兩種作法的意思差不多  相信您很快就可以理解
第一個作法做完之後rebase onto main就會等於第二種

另外也有人習慣在功能還沒開發完成前把branch取叫`4-navs-for-guest-wip`或是`4-navs-for-guest-2`
等功能做完之後再推真正的`4-navs-for-guest`到remote  最後把那個暫時的`-wip`或是`-2`從remote刪掉
哪種作法都行  總之您自己建立的branch要怎麼搞都可以

**Comment by PatrickKuei** [comment]
報告是史蒂芬哥 我最喜歡抱著搞 有時候喜歡背對著搞 跟大奶妹想怎麼搞都喜歡史蒂芬哥
已經把那個沒用的２刪除了 通通刪掉 ２成這樣還敢待在我們史蒂芬哥大師的repo裡面啊
下一個branch可以試試wip 這樣區分感覺挺好的
