### ISSUE TITLE
Navs for guest

### ISSUE THREAD

**Issue by abemscac** [abemscac/inet-PatrickKuei#4]
樣板: https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=74%3A807

![Screen Shot 2022-04-21 at 9 01 52 AM](https://user-images.githubusercontent.com/59676941/164350961-01476562-5c74-42ae-ad1c-328e2e4f8279.png)

請注意，這個issue只需要做遊客的navs。

**目標**

- [x] 在桌面尺寸，上方navbar會出現：
  - logo
  - 搜尋欄位 ([Input](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=37%3A116)元件)
  - 登入按鈕 ([Button](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=1%3A22)元件)
  - 註冊按鈕
- [x] 在行動尺寸，上方navbar會出現：
  - 開啟左側選單按鈕
  - logo
  - 搜尋欄位
  - 開啟遊客dropdown的按鈕
- [x] 左側選單裡面會出現：
  - 登入按鈕
  - 註冊按鈕
  - 討論板列表
- [x] 左側選單開啟時背景應該要變黑。
- [x] 遊客dropdown([Dropdown](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=37%3A366)元件)裡面會出現：
  - 註冊選項
  - 登入選項

**Comment by abemscac** [comment]
@PatrickKuei 報告patrick哥
有些元件不見得馬上就要做成共用的component  例如navbar上面的input
因為現在只有出現一次  所以您可以直接把它寫在navbar上面
我們永遠可以藉由重構程式碼來把那些該共用的東西從非共用轉成共用
我發現這樣的開發速度會快一些  不會過度思考/過度設計
就算您知道這個input最後會需要5個props  但是現在只用到2個
可以只做用到的那2個就好  另外3個等真正用到了再來refactor  會讓事情變得比較簡單. 不過這只是建議
如果這些東西對您來說其實挺容易的
那也可以一次把它做完  完全沒問題

**Comment by PatrickKuei** [comment]
沒問題史蒂芬哥
已經把最新進度push上來了 大概完成task1的４％
４％粉 抓到 
這樣使用tailwindcss不曉得史蒂芬哥您覺得如何
figma內的pixel都找不到相對的css utility 所以目前都是找看起來差不多的
實際上該用哪些utility我覺得史蒂芬哥您若較忙 可以等我發pr再幫我review就行了

另外報告史蒂芬哥 感覺button的共用元件製作會比較棘手一些
目前先照您說的先不想太多 把速度拉起來 素肚插起來 可能等task做到一個段落再來搞搞共用

**Comment by PatrickKuei** [comment]
報告是 立正稍息立正 營長好
阿斯太好了史蒂芬哥 那我就繼續往下做了
不過剛剛看了一下搜尋的input有一個bug
我目前是用flex把兩個div合在一起 各把相接面border取消 假裝他們兩個是一個input
但是這樣還得去照顧:focus的style之類的後續東西
<img width="537" alt="image" src="https://user-images.githubusercontent.com/48916128/165266945-cbe29561-6ddb-42c4-8e77-179ceb873714.png">

網路上提供的另一種辦法是用absolute/relative來把icon重疊上input
我沒有去用是因為覺得這樣重疊有點髒 但是好處是應該不用管之後focus等等的style
因為以前antd boobstrap都有附帶icon的input能用 幾乎沒有自己刻過
不曉得史蒂芬哥您覺得怎麼做比較好呢

另外報告史蒂芬哥
關於 2 的部分 一語道破夢中人 真的是太久沒有寫正常的react了 都忘記svg可以變成component了
關於 3 的部分 剛剛仔細看tailwindcss doc裡面的default spacing scale好像就是４的倍數史蒂芬哥
    1 = 4px
    2 = 8px
    3 = 12px
只不過他還有0.5 1.5 2.5 3.5 但也就只有到3.5而已了
從來沒有用過rem史蒂芬哥
看到網路上說 ‘CSS rem stands for “root em“’
也就是說如果我直接改html tag的font-size 他就會一起變大變小嗎
不曉得使用rem是業界常態嗎 我司目前看起來都還是直接用px 但我沒有深入去看 也沒負責到所以不曉得是我看到的那邊才用px 還是全部都是

**Comment by PatrickKuei** [comment]
報告史蒂芬哥
關於button style的部分也想請教一下
<img width="242" alt="image" src="https://user-images.githubusercontent.com/48916128/165289006-46fc5eb2-9516-4941-8f21-7bb19a712036.png">
我原本是直接看navbar那邊的button的長寬去寫目前的button長寬
但在寫共用button的時候仔細想想好像不太對 寫死寬度的話如果字數太多不就爆開了嗎 難不成每次都要重新給寬度 這樣有點怪
我就研究了一下設計圖裡面全部的button
我在想是不是高度以大小區分寫死 寬度不寫 只需要寫死padding: 32px 就好了？
然後再分成只有文字的button / 有文字和Icon的button / 只有Icon的button 去給不同的padding 這樣

**Comment by abemscac** [comment]
@PatrickKuei 晚點名
我愛中華  我愛中華
1212  預備  唱

> 網路上提供的另一種辦法是用absolute/relative來把icon重疊上input
> 我沒有去用是因為覺得這樣重疊有點髒 但是好處是應該不用管之後focus等等的style

報告patrick哥  剛開始看的確覺得髒沒錯  心裡會覺得那個不是作弊的寫法嗎  不好吧
不過style寫多了之後就會發現relative+absolute是超常見的組合  很多東西真的只有他們能幫我們做到
例如我司的這個[FrontRow](https://collectfrontrow.com/)網站  裡面有為數眾多的relative+absolute
上面那個是prod版本  很多頁面都被關閉了  其實dev版本這裡還有超多的relative+absolute
有lading page的網站因為要照顧到各種尺寸的裝置  所以一定都有大量的relative+absolute  這是正常的
您可以把relative和absolute當成是工具  工具本身並沒有好壞  是好是壞全看使用工具的人怎麼用  用在哪裡
所以不必太在意  放心ㄟ伯捨路下去就對了
[我們的input](https://www.figma.com/file/BedgjiZTHBbZYcd0WqaqtE/Mockup?node-id=37%3A116)是做成像material design那種有[浮動label](https://material.io/components/text-fields#interactive-demo)的  所以也會用到relative+absolute

> 看到網路上說 ‘CSS rem stands for “root em“’
> 也就是說如果我直接改html tag的font-size 他就會一起變大變小嗎

報告沒錯patrick哥  rem是相對的數值  會跟著parent設定的值一起變化
聽起來不錯  不過我也沒實際用過他  沒什麼有用的經驗能分享
我司也都是直接px  沒在用em/rem  我也不確定是否大多數的公司都這樣
不過我司老闆身經百戰  也常常在學習新技術  他也都是一路px始終如一
所以我也跟著px  沒去試em/rem  不知道裡面到底是什麼情況

> 比方說這邊的INET logo 在mobile模式要消失 變成一個 i 的logo
> 我是弄一個media 讓他display: none/block 切換嗎
> 還是也生一個isMobile的值 寫成這樣 isMobile ? <MobileLogo /> : <DesktopLogo /> 呢

isMobile是指從script去抓window.innerWidth  然後控制element是否要顯示嗎
CSS能解決的東西通常我都是用CSS  比較直觀
script處理商業邏輯比較多  跟style有關的東西能少就少
script去控制CSS在某些情況的確很讚(例如：製作carousel)  但是以這個logo我認為CSS較佳
tailwind有些屬性可以加上modifier  [display也有](https://tailwindcss.com/docs/display#breakpoints-and-media-queries)
所以我的話會做成大螢幕和小螢幕的logo本來就在那裡  只是看他有沒有顯示出來而已
ailwind的內建class就可以解決大部分的事情  省時省力

> 我在想是不是高度以大小區分寫死 寬度不寫 只需要寫死padding: 32px 就好了？
> 然後再分成只有文字的button / 有文字和Icon的button / 只有Icon的button 去給不同的padding 這樣

差不多意思patrick哥  我們的button只要是同size  不管他的variant/fill-type/icon是什麼值都會是同個高度  但是寬度會隨著content變化
所以您可以根據size把高度寫死  然後x軸的padding寫好即可
純icon的button甚至可以寬高都寫死  完全沒問題
有兩個東西非常建議您熟悉+當成做style時的預設規則  也許您都學過了
第一個是[border-box: box-sizing](https://www.w3schools.com/css/css3_box-sizing.asp)  建議您把全部的element都套上這個屬性值
第二個是[flexbox layout](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)和[gap](https://www.w3schools.com/cssref/css3_pr_gap.asp)
這兩個東西的用處非常之大  跟奶子差不多大
熟悉了之後我想可以做到超過8成的layout沒問題
我們的button/input等等太多東西都可以用flexbox來做  可以好好利用

**Comment by PatrickKuei** [comment]
報告沒問題史蒂芬哥
已經把一些您提到的東西都改上去了 包括有去確認tailwincss預設所有元素套用border-box
<img width="761" alt="image" src="https://user-images.githubusercontent.com/48916128/165479869-811130fd-61ef-4ac4-8be0-a9e51c3c7570.png">

另外報告史蒂芬哥 除了category的圖片我要再重新用<img>配jpg 看看會不會修好以外
目前遇到一個問題不知道怎麼處理
就是在mobile時 打開sidebar 後面會有一層半透明黑色的遮罩的部分
印象中先前做dialog時好像有用過啥porter把元件送到root
不太清楚這種遮罩是不是也該這樣做
我試著用z-index把他跟sidebar弄到９９跟９９９都沒啥變化 
不曉得史蒂芬哥您通常都怎麼做遮罩的部分？

再來是ts的部分史蒂芬哥
<img width="518" alt="image" src="https://user-images.githubusercontent.com/48916128/165482607-4b78a5aa-e5eb-46eb-aba3-f74ff6993f00.png">
不知道是我太久沒有寫了還是第一次搭配eslint
我為了在div上面用上onClick 要加上一大堆參數 什麼role, tabIndex 還強迫我加上onKeyDown
是我哪邊用錯了嗎 還是這本來就該這樣？？

另外雖然figma沒有特別註明
但看起來關閉sidebar是透過點擊那個半透明灰色的部分對吧？

最後就是報告史蒂芬哥 雖然figma上有提到sidebar list hover style
但是我其實不知道手機上要怎麼實現hover狀態 每次按一按就點進去了 就像管不住的分身一樣 每次出去晃兩下就滑進去了
阿斯
真想跟年輕ＪＫ一起滑進魔鐵裡面研究REACT史蒂芬哥
這個REACT究竟如何REACT 太深奧了

**Comment by abemscac** [comment]
> 就是在mobile時 打開sidebar 後面會有一層半透明黑色的遮罩的部分
> 印象中先前做dialog時好像有用過啥porter把元件送到root
> 不太清楚這種遮罩是不是也該這樣做

報告是patrick哥  dialog的東西我也建議用[portal](https://reactjs.org/docs/portals.html)來做
Dialog可能會被放到dom tree的很裡面  單純用absolute + 寬高100%的話不安全
因為absolute會一層一層往上找  如果找到一個`display: relative`的parent那absolute的100%就會變成那個container的100%  而非整個螢幕的100%
所以建議您在很上層的地方(最常見的是body的第一層children)加一個dialog的container  全部的dialog都可以portal到那個容器裡面去
每個dialog都會包含黑色背景+白色內容兩塊  所以一個dialog大概會是這樣

```html
<div className="my-dialog">
  <黑色那一塊 className="absolute w-full h-full" />
  <白色那一塊 className="...">
    <內容 />
  </白色那一塊>
</div>
```

值得注意的是用utility-css不代表完全不能出現`my-dialog`這種自定的css
如果tailwind拼湊不出來或是很難拼  那也可以直接寫custom class
只要簡單好讀好維護就是好方法

> 我為了在div上面用上onClick 要加上一大堆參數 什麼role, tabIndex 還強迫我加上onKeyDown

我也不知道這是3小patrick哥
估狗一下之後發現這是React喜愛的[無障礙(accessibility)](https://reactjs.org/docs/accessibility.html#why-accessibility)的一部分
我才看沒幾分鐘  還不是很瞭解  但是我覺得的確有他的道理在
您看見錯誤的原因是`<div>`加上`onClick`在某個層面上(我不知道是哪個層面)不是一個直觀的組合
如果一個東西可以被點擊  那`<button>`或是`<a>`這種tag比較適合他  您可以參考[這裡](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-element-interactions.md)
如果您用semantic HTML(語義化HTML)的角度來寫網頁  應該可以避免掉不少類似的怪問題
我也建議您將這個div改成button  畢竟設計時的本意真的就是把它看成一個按鈕
但是這種div + onClick的組合我想在現今業界肯定比比皆是  我司就有不少這種寫法
所以如果您現在不想管這個  您也可以修改`.eslintrc.json`把這類的訊息隱藏起來  我認為也是合理的
至少Vue官方沒有管這個  看來目前只有React硬上

> 另外雖然figma沒有特別註明
> 但看起來關閉sidebar是透過點擊那個半透明灰色的部分對吧？

報告是patrick哥  真是太聰明了
我應該加個X在選單右上角之類的
之後有空把它加上去  感謝patrick哥

> 我其實不知道手機上要怎麼實現hover狀態 每次按一按就點進去了

報告patrick哥  手機的focus的確跟我們想的不一樣
他要按著那個東西直到選單跑出來  才會進入focus狀態
網頁是default -> :hover -> (點擊) -> :active
但是手機是default -> (點擊) -> :active -> (不要放掉) -> (選單跑出來) -> :hover
所以您可以忽略手機sidebar那個focus效果
Figma那裡那樣子寫只是為了讓他跟首頁左邊的選單設計相符  卻忘了手機根本沒有focus
看來我的修行還不夠  只好放兩顆小饅頭在這裡向您賠罪了
https://i.redd.it/of1uw0tms1w81.jpg

**Comment by abemscac** [comment]
@PatrickKuei 報告patrick哥
我發現我最早commit上來的那個.gitignore竟然把`.vscode/settings.json`也ignore了
真是太不應該了  您下次commit的時候能否順便把它從.gitignore移掉

另外上次review的時候忘了在.prettierrc.json裡面加`tabWidth: 數字`
看您個人喜歡2還是4  個人建議是2
有些複雜的邏輯會有比較多層的程式碼  2會比較好讀一點
不過這是個人喜好  所以選一個您中意的即可

感恩patrick哥  讚嘆patrick哥
https://i.imgur.com/HCztN80.gifv

**Comment by abemscac** [comment]
報告patrick哥
可以的話順便加一下.vscode資料夾裡面vscode的設定  我之前通通忘了
跟某鬼島國人民一樣健忘

- `.vscode/settings.json`
    我記得我們之前只有設formatOnSave  沒有設defaultFormatter
    建議把之前那個`"[typescript]"`的限制拿掉  讓這些設定套用到所有語言的檔案上
    不管他開的是什麼檔案  只要是這個workspace的檔案通通用prettier format起來  #一點都不能少
    ```json
    {
      "editor.defaultFormatter": "esbenp.prettier-vscode",
      "editor.formatOnSave": true
    }
    ```
- `.vscode/extensions.json`
    ```json
    {
      "recommendations": ["esbenp.prettier-vscode", "dbaeumer.vscode-eslint"]
    }
    ```

**Comment by PatrickKuei** [comment]
> @PatrickKuei 報告patrick哥 我發現我最早commit上來的那個.gitignore竟然把`.vscode/settings.json`也ignore了 真是太不應該了 您下次commit的時候能否順便把它從.gitignore移掉
> 
抱歉史蒂芬哥 看起來應該是我把.vscode/settings名字打錯了少了一個s 所以才沒有無視掉
已經改過自信 對媽祖發誓退出政壇
https://imgur.com/kuizrPN

> 報告patrick哥 可以的話順便加一下.vscode資料夾裡面vscode的設定 我之前通通忘了 跟某鬼島國人民一樣健忘
> 
> * `.vscode/settings.json`
>   我記得我們之前只有設formatOnSave  沒有設defaultFormatter
>   建議把之前那個`"[typescript]"`的限制拿掉  讓這些設定套用到所有語言的檔案上
>   不管他開的是什麼檔案  只要是這個workspace的檔案通通用prettier format起來  #一點都不能少
這個沒有問題史蒂芬哥 之前就有這樣加了 一個都不能少 一滴的不能露出來 給我吞 我叫你吹
阿斯 不曉得我們田大少爺現在過得怎麼樣了 一定又開著名車在草屯山路上奔馳吧 有錢人的生活就是這麼樸實無華

**Comment by abemscac** [comment]
要跟我們宋伯伯一樣七進七出政壇了嗎patrick哥
退出政壇唯一榜樣我只服曲棍球
報告patrick哥  實際上我們不想要他ignore
那些.vscode的設定必須被commit上來  才能達到我們統一的目的
臉盆鞋子皂盒牙刷該往哪個方向擺就往哪個方向擺  你各位不要給我客製化
所以結論是不要ignore  要通通推上去才對

**Comment by PatrickKuei** [comment]
報告是史蒂芬哥 是幽默啦
![image](https://user-images.githubusercontent.com/48916128/165672337-9a4dd062-022b-4e82-a4d1-cd14b34fb786.png)
我說錯了 改了名字之後就會不無視了才對
因為史蒂芬哥您之前有設定這一段
<img width="548" alt="image" src="https://user-images.githubusercontent.com/48916128/165672410-e161dbc7-e8d4-4445-889b-eb29796cc798.png">
照理來說應該會不無視 我左看右看 查了一下到底為啥還是被無視 才發現原來是我名字取錯了
她小娘子目前已經被我好好地釘在牆上準備上下其手了 您不用擔心
<img width="846" alt="image" src="https://user-images.githubusercontent.com/48916128/165672489-46e83f2b-7a76-415c-b2f0-958ca8b2162b.png">

**Comment by abemscac** [comment]
原來魯此patrick哥
我國的政要真是太有幽默感了  好幸福
那個.gitignore好像是github還是哪裡生成的  我也沒注意他裡面有加

**Comment by PatrickKuei** [comment]
> 但是手機是default -> (點擊) -> :active -> (不要放掉) -> (選單跑出來) -> :hover
所以您可以忽略手機sidebar那個focus效果

報告史蒂芬哥 這邊說的focus效果
是指深藍色食物這一塊嗎 就像內湖新店一樣深藍
<img width="336" alt="image" src="https://user-images.githubusercontent.com/48916128/165724937-767ab3ed-a77c-46c6-b487-91e7f70e553c.png">
> 但是手機是default -> (點擊) -> :active -> (不要放掉) -> (選單跑出來) -> :hover

那個選單跑出來是手機的預覽功能嗎 
因為我在iphone上點著不放掉 會跳出小視窗 裡面會讀取點進去的頁面 跟一個iphone內建功能的menu 有啥打開拷貝分享之類的
但是hover不會出來 不知道是不是iphone比較特別

另外報告史蒂芬哥
目前畫面部分還差關閉sidebar按鈕 一些打開關起來時的動畫 還有更細節的style/interaction style
我有稍微做一個sidebar關閉按鈕先擋著用 動畫的部分可能加入個transition-duration之類的
api還沒有串 之後串好可能還會再修改一下畫面
不曉得這樣可以先發pr嗎 還是等上面那些東西補全了再發呢

**Comment by abemscac** [comment]
> 這邊說的focus效果是指深藍色食物這一塊嗎

報告patrick哥  我說錯了
我要說的是hover才對  不是focus
focus是另外一種狀態  真是太不應該了 https://www.redgifs.com/watch/complexpartialbrahmancow

> 那個選單跑出來是手機的預覽功能嗎

我是用chrome的手機尺寸按的  我剛剛發現他那個選單其實就是滑鼠的點右鍵
安卓這裡點下去就hover了  長按的話什麼事都不會發生

> 這樣可以先發pr嗎 還是等上面那些東西補全了再發呢

報告patrick哥  您會有這樣的困擾是因為我們的怡秀涵蓋太多東西了
這個navbar可以拆成很多個小issue  但是我就懶
管理專案真的是太麻煩了  所以我大爆塞一次塞滿滿
東西太多的話他們會做到一個段落就先建PR  剩下沒做完的再開另外一個issue
PR發出來之後不會讓他掛在那邊太久  會優先處理
但是這裡也才我們兩個  我們可以滾動式修正patrick哥
您可以直接建PR  然後再慢慢review -> 修正 -> 開發直到這個怡秀完成
完全沒問題

另外看起來 `"security.workspace.trust.untrustedFiles": "open"` 這個危險的設定只能讓開發者自己從vscode打開
沒辦法強制注入

<img width="680" alt="image" src="https://user-images.githubusercontent.com/59676941/165747306-4d4f032d-0456-4e2c-ae6a-51ece8dd23ee.png">

您可以順便把它夾掉  痛
感謝patrick哥
